### PR TITLE
Configured .prettierrc and installed prettier

### PR DESCRIPTION
**Pull request by rudream**
Installed prettier into the project and set up the .prettierrc.json config file. This is to prevent unnecessary merge conflicts due to different formatting settings between team members.

Instructions for team members (please do this before your pull request, so that every file getting merged into dev is formatted properly when you push it):

NOTE: You only have to follow these steps once.

1. Pull and merge this into your local
2. Run `$ npm install` in both /client and /server to install the prettier module
3. Run `$ npx prettier --write . ` in the root folder of the repo to format all the files properly (this might take some time, but you only have to do it once)
4. Make sure you have `"editor.formatOnSave": true,` in your vscode settings.json
5. You're good to go 👍 

Thanks!

### CODE REVIEW

**Review by jessdesr — APPROVED** [review]
Nice!  Maybe post the steps in slack so everyone sees it.

**Comment by rudream** [comment]
> Nice! Maybe post the steps in slack so everyone sees it.

Yes I did already 😄

**Comment by jessdesr** [comment]
> > Nice! Maybe post the steps in slack so everyone sees it.
> 
> Yes I did already 😄

Excellent!  Go ahead and merge

**Comment by rudream** [comment]
> > > Nice! Maybe post the steps in slack so everyone sees it.
> > 
> > 
> > Yes I did already 😄
> 
> Excellent! Go ahead and merge

Thank you!

**Pull request merged**
